include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - sized_box_for_whitespace
    - unnecessary_const
    - unnecessary_new
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - empty_constructor_bodies