name: local_hero_deneme
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.12
  just_audio: ^0.9.20
  #image: ^3.1.1
  #file_picker: ^4.3.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/1/
    - assets/2/
    - assets/3/
    - assets/4/
    - assets/Tile Move.wav
    - assets/Not Movable.wav
    - assets/Shuffle-Reset.wav
    - assets/Color Change.mp3
    - assets/Choir Harp Bless.wav
    - assets/Theme Change.wav

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/Manrope-Light.ttf
